# Generated by Django 4.1.7 on 2023-03-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('homework_name', models.CharField(max_length=45)),
                ('homework_description', models.CharField(max_length=45, null=True)),
                ('deadline', models.DateField()),
                ('start', models.DateField()),
                ('room', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('email', models.CharField(max_length=45)),
                ('room', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=65)),
                ('credit', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homeworks.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student_has_Homework',
            fields=[
                ('stu_hw_id', models.AutoField(primary_key=True, serialize=False)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homeworks.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homeworks.student')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homeworks.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homeworks.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Nofitication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=12)),
                ('start', models.DateField()),
                ('deadline', models.DateField()),
                ('stu_hw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homeworks.student_has_homework')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homeworks.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homeworks.teacher'),
        ),
    ]
