# Generated by Django 4.1.7 on 2023-03-06 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworks', '0002_stu_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='score',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Homeworks.subject'),
            preserve_default=False,
        ),
    ]
