# Generated by Django 4.1.7 on 2023-03-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworks', '0003_homework_score_homework_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='start',
        ),
    ]
