# Generated by Django 4.1.7 on 2023-03-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworks', '0005_alter_homework_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stu_homework',
        ),
    ]
