# Generated by Django 4.1.7 on 2023-03-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworks', '0006_delete_stu_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_has_homework',
            name='status',
            field=models.CharField(default='InProgress', max_length=30),
        ),
    ]
