# Generated by Django 4.1.7 on 2023-03-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworks', '0007_student_has_homework_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
